const ColorStyles = {
    'tree': '#e8c7c7',
    'graph': '#d8a3a3',
    "arc_diagram":'#d8bea3',
    'treemap': '#c87e7e',
    'hierarchical_edge_bundling': '#b85a5a',
    'sunburst_icicle': '#a93636',
    'line_chart': '#d8bea3',
    'parallel_coordinate': '#c8a47e',
    'polar_plot': '#b88a5a',
    'storyline': '#a97036',
    'flow_diagram': '#c8c87e',
    'chord_diagram': '#b8b85a',
    'sankey_diagram': '#a9a936',
    'map': '#70a936',
    'heatmap': '#7ec87e',
    'heatmap_matrix': '#a93670',
    'heatmap_map': '#a93670',
    'unit_visualization': '#5ab85a',
    'glyph_based': '#36a936',
    'scatterplot': '#36a970',
    'matrix': '#7ec8c8',
    'table': '#5ab8b8',
    'small_multiple': '#36a9a9',
    'pie_chart': '#7ea4c8',
    'sector_chart': '#5a8ab8',
    'donut_chart': '#3670a9',
    'error_bar': '#7e7ec8',
    'box_plot': '#5a5ab8',
    'stripe_graph': '#3636a9',
    'bar_chart': '#7036a9',
    'area_chart': '#b85ab8',
    'proportional_area_chart': '#a936a9',
    'word_cloud': '#a93670',
    "contour_graph":'#d8bea3',
    "surface_graph":'#b88a5a',
    "vector_graph":'#a97036',
    'scivis':'#c8c87e',
    'others': '#d3d3d3',
    
    'repeated': "#1f77b4",
    'stacked': "#1f77b4",
    'mirrored': "#1f77b4",
    'large_view': "#e28034",
    'coordinated': "#e28034",
    'annotated': "#e28034",
    'accompanied': "#e28034",
    'nested': "#519c3e"
}


const TextTranslate = {
    'area_chart': 'area chart',
    'bar_chart': 'bar chart',
    'box_plot': 'box plot',
    "arc_diagram":'arc diagram',
    "contour_graph":'contour graph',
    'chord_diagram': 'chord diagram',  
    'donut_chart': 'donut chart',
    'error_bar': 'error bar',
    'flow_diagram': 'flow diagram',
    'glyph_based': 'glyph based',
    'graph': 'graph',
    'heatmap': 'heatmap',
    'heatmap_matrix': 'heatmap matrix',
    'heatmap_map': 'heatmap map',
    'hierarchical_edge_bundling': 'hierarchical edge bundling',
    'line_chart': 'line chart',  
    'matrix': 'matrix',
    'map': 'map',
    'others': 'others',
    'parallel_coordinate': 'parallel coordinate',
    'pie_chart': 'pie chart',
    'polar_plot': 'polar plot',
    'proportional_area_chart': 'proportional area chart',
    'sankey_diagram': 'sankey diagram',
    'scatterplot': 'scatterplot',
    'scivis':'scivis',
    'sector_chart': 'sector chart',
    'small_multiple': 'small multiple',
    'storyline': 'storyline',
    'stripe_graph': 'stripe graph',
    'sunburst_icicle': 'sunburst icicle',
    "surface_graph":'surface graph',
    'table': 'table',
    'tree': 'tree',
    'treemap': 'treemap',
    'unit_visualization': 'unit visualization',
    "vector_graph":'vector graph',
    'word_cloud': 'word cloud',
}

const LabelToName = {
    "area_chart":"Area",
    "arc_diagram":'Arc',
    "bar_chart":"Bar",
    "box_plot":"Box",
    "comb":"Composite",
    "contour_graph":"Contour",
    "chord_diagram":"Chord",
    "donut_chart":"Donut",
    "error_bar":"Error Bar",
    "flow_diagram":"Flow",
    "glyph_based":"Glyph",
    "graph":"Graph",
    "heatmap":"Heatmap",
    'heatmap_matrix': 'Heatmap Matrix',
    'heatmap_map': 'Heatmap Map',
    "hierarchical_edge_bundling":"HEB",
    "line_chart":"Line",
    "map":"Map",
    "matrix":"Matrix",
    "node_link":"Node-link",
    "parallel_coordinate":"PCP",
    "pie_chart":"Pie",
    'polar_plot': 'Polar',
    "proportional_area_chart":"PAC",
    "radar_chart":"Radar",
    "sankey_diagram":"Sankey",
    "scatterplot":"Scatter",
    "scivis":"SciVis",
    "sector_chart": 'Sector',
    "small_multiple":"Small Multiples",
    "storyline":"Storyline",
    "stripe_graph":"Stripe",
    "sunburst_icicle":"Sunburst/Icicle",
    "surface_graph":"Surface",
    "table":"Table",
    "tree":"Tree",
    "treemap":"Treemap",
    "unit_visualization":"Unit",
    "vector_graph":"Vector",
    "word_cloud":"Word Cloud",
    'overlaid': 'Overlaid',
    'juxtaposed': 'Juxtaposed',
    'repeated':'Repeated','stacked':'Stacked','mirrored':'Mirrored','accompanied':'Accompanied',
    'large_view':'Large Panel','annotated':'Annotated','coordinated':'Coordinated','nested':'Nested',
    'coOccurrence': 'Co-occurrence',
    "others":"Others",
    'InfoVis': 'InfoVis',
    'VAST': 'VAST',
    'Vis': 'Vis',
    'SciVis': 'SciVis',
    null: 'Any Types'
}

const ReverseTextTranslate = {};
Object.keys(TextTranslate).forEach(key => ReverseTextTranslate[TextTranslate[key]] = key);

const ReverseLabelToName = {};
Object.keys(LabelToName).forEach(key => ReverseLabelToName[LabelToName[key]] = key);

export { ColorStyles, TextTranslate, ReverseTextTranslate, LabelToName, ReverseLabelToName };
